# For more informations, please read official documentation -> https://docs.travis-ci.com/user/languages/android/
sudo: required

language: android
jdk: oraclejdk8

install: true

before_cache:
  - rm -rf $HOME/.gradle/*
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

env:
 global:
 - ANDROID_API_LEVEL=27
 - ANDROID_BUILD_TOOLS=26.0.2

 
android:
  components:
  - tools
  - platform-tools
  - tools # Running this twice get's the latest build tools (https://github.com/codepath/android_guides/wiki/Setting-up-Travis-CI)
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API_LEVEL
  - extra
licenses:
  - '.+'
before_script:
  - chmod +x gradlew 

script:
  - ./gradlew clean test build
