version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: "-Xmx4096m -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2"
    steps:
      - run:
          name: Lists installed targets
          command: android list target
          environment:
            TERM: dumb

      - run:
          name: List available targets and other sdk modules
          command: sdkmanager --list --include_obsolete --verbose
          environment:
            TERM: dumb

      - run:
          name: Create avd
       #   command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-27;google_apis;armeabi-v7a"
          command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-24;default;armeabi-v7a"
          environment:
            TERM: dumb

      - run:
          name: Start emulator
          command: /opt/android-sdk-linux/emulator/emulator -avd testEmulator -no-audio -no-window
          background: true
          environment:
            TERM: dumb 

      - checkout

      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}   

      - run:
          name: Wait for emulator
          command: ./android-wait-for-boot.sh
          environment:
            TERM: dumb

      - run:
          name: Remove lock screen
          command: adb shell input keyevent 82
          environment:
            TERM: dumb

      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Instrumentation testing
          command: ./gradlew connectedCheck
          environment:
            TERM: dumb

      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results